### ISSUE TITLE
想做一个pycharm的汉化包

### ISSUE THREAD

**Issue by ghost** [ewen0930/WebStorm-Chinese#10]
想请教作者是如何识别各种字段的，用到的工具都有哪些？如何更改？

**Comment by ewen0930** [comment]
PyCharm也做了一个汉化版， https://github.com/ewen0930/PyCharm-Chinese
你想更进一步的汉化，可以使用 Passolo,找篇介绍说明文章看看……
语言资源文件在libs/resources_en.jar里，直接用工具扫描 resources_zh.jar 里的messages目录即可

**Comment by ghost** [comment]
好的，谢谢

**Comment by ghost** [comment]
我的是osx系统，估计用不了Passolo，而且也不适合这个包估计，不过还是谢谢作者，提供了一个思路
