### ISSUE TITLE
期待更新

### ISSUE THREAD

**Issue by mangaojian** [ewen0930/WebStorm-Chinese#13]
什么时候更新下版本，完善下汉化包

**Comment by ewen0930** [comment]
最新汉化包是2017.1，适用于2017.1.1；
菜单和资源包的词汇并不是一一对应的，有些就是没有对应资源；
完善度可能就这样，每次更新尽量新增几条，不影响使用！

**Comment by mangaojian** [comment]
问个问题，汉化文件的字符串转换成ASCII码的原因是什么？

**Comment by ewen0930** [comment]
工具自动输出的，应该是避免乱码吧！

**Comment by mangaojian** [comment]
首选项 > 编辑器 > 通用 > 自行换行 > use original line's indent for wrapped parts
后面这句要翻译哪个文件，我搜索出来的结果是resources_en/search/searchableOptions.xml这个文件里有这一句，但觉得应该不是翻译这个文件

**Comment by ewen0930** [comment]
你可以试试！菜单和资源包的词汇并不是一一对应的……
