### ISSUE TITLE
能不能出一个如何进行汉化的教程？

### ISSUE THREAD

**Issue by kosuke-zhang** [ewen0930/WebStorm-Chinese#14]
我想参与进来对jetbrains的几个软件进行完全的汉化，但不知道怎么操作，作者能不能提供一个教程，非常想参与啊！！！

**Comment by ewen0930** [comment]
不要期望全部翻译，界面里本身有大量词汇和语句，资源文件里并没有；
有些词汇翻译了，会影响到软件的功能；
目前的翻译保证理想的可视效果，同时不影响使用即可；

想学习翻译制作中文包：首先找一份 Passolo 的使用说明了解一下；
然后参考: https://github.com/ewen0930/WebStorm-Chinese/issues/8 和 https://github.com/ewen0930/PyCharm-Chinese/issues/5

**Comment by SuvanCheng** [comment]
我也想采用
