### ISSUE TITLE
汉化包添加进去后发现文档定位功能不见了

### ISSUE THREAD

**Issue by kongjiea** [ewen0930/WebStorm-Chinese#4]
也就是scroll from source的按钮不见了。
还有文档全部收缩 collapase all按钮也不见了。。。

**Comment by ewen0930** [comment]
初期使用了大量自动翻译，确实会出现功能不正常的情况！
是WebStorm吗，我没找到scroll from source，是这么拼写的吗？只有 Autoscroll from Source

**Comment by kongjiea** [comment]
@ewen0930 拼写没错啊，就是左侧侧栏的右上角的几个按钮啊，这里也不好发图片，好不你弄个邮箱，qq群，或者qq我发给你。。。

**Comment by ewen0930** [comment]
那你发个截图到 ewen0930(at)qq.com 吧，英文版我也没看见

**Comment by ewen0930** [comment]
你试试吧， 好折腾！！
https://github.com/ewen0930/WebStorm-Chinese/releases/tag/0.6.4-beta-v9.0.2

**Comment by kongjiea** [comment]
@ewen0930 灰常感谢，你做的已经灰常不错了。。
