### ISSUE TITLE
小白想参与

### ISSUE THREAD

**Issue by maicWorkGithub** [ewen0930/WebStorm-Chinese#8]
能不能给个文件对照表什么的，我也想帮助开发一下。有点笨，找不到对照关系。

**Comment by ewen0930** [comment]
直接用 SDL Passolo 扫描对应的目录即可，繁体的是用的 Passolo 插件自动处理的，未校对

**Comment by maicWorkGithub** [comment]
我擦，1940英镑一个的软件...

**Comment by maicWorkGithub** [comment]
我解压了resources_en.jar文件之后出现了跟从你的仓库里下载的文件一样的东西，但是还是用不了Passolo这个软件，是软件不会用，指定格式的文件没有找到。请问哪里有教程？我搜到的只有官方的，网速慢的要死，还没找到可用的。

**Comment by ewen0930** [comment]
解压后，用Passolo创建中文翻译，再把我的 resources_zh.jar 解压，用Passolo扫描对应的目录……
